Repository 2025-Techeer-Summer-BootCamp-Team-E/backend, pull requests merged in 2025-07, with the labels that each got.

#8 [Feat] 대본생성 기능 구현
  backend_django/books/__init__.py
  backend_django/books/admin.py
  backend_django/books/apps.py
  backend_django/books/migrations/0001_initial.py
  backend_django/books/migrations/__init__.py
  backend_django/books/models.py
  backend_django/books/tests.py
  backend_django/books/urls.py
  backend_django/books/views.py
  backend_django/characters/__init__.py
  backend_django/characters/admin.py
  backend_django/characters/apps.py
  backend_django/characters/gpt_client.py
  backend_django/characters/migrations/0001_initial.py
  backend_django/characters/migrations/__init__.py
  backend_django/characters/models.py
  backend_django/characters/tests.py
  backend_django/characters/urls.py
  backend_django/characters/views.py
  backend_django/config/settings.py
  backend_django/config/urls.py
  backend_django/requirements.txt
Labels: feat

#17 [Devops] Traefik 설정
  .gitignore
  backend_django/config/settings.py
  backend_django/docker-compose.yml
  backend_django/infra/docker-compose.yml
Labels: devops

#19 [fix] 배포 호스트 명시
  backend_django/config/settings.py
Labels: devops

#27 [fix]Traefik 설정, 개발용과 배포용 환경변수 수정
  .gitignore
  backend_django/config/settings.py
  backend_django/docker-compose.yml
  backend_django/infra/docker-compose.yml
Labels: devops

#39 [Feat] 나레이션 기능 구현
  backend_django/Dockerfile
  backend_django/characters/gpt_client.py
  backend_django/characters/views.py
  backend_django/config/urls.py
  backend_django/narration/__init__.py
  backend_django/narration/admin.py
  backend_django/narration/apps.py
  backend_django/narration/common/__init__.py
  backend_django/narration/common/s3_client.py
  backend_django/narration/migrations/__init__.py
  backend_django/narration/models.py
  backend_django/narration/service/__init__.py
  backend_django/narration/service/tts_service.py
  backend_django/narration/table/__init__.py
  backend_django/narration/table/tts_voice_map.py
  backend_django/narration/tests.py
  backend_django/narration/urls.py
  backend_django/narration/views.py
  backend_django/narration/voice_selector.py
Labels: feat

#47 feat:공용책 목록 불러오기 기능 구현
  backend_django/books/serializers.py
  backend_django/books/urls.py
  backend_django/books/views.py
  backend_django/config/settings.py
Labels: feat

#49 [devops] Portainer, 모니터링 설정
  backend_django/config/settings_prod.py
  backend_django/config/urls.py
  backend_django/docker-compose.prod.yml
  backend_django/prometheus/prometheus.yml
  backend_django/promtail/config.yml
Labels: devops

#52 [Feat] 책 하나 당 영상 목록 조회
  backend_django/books/serializers.py
  backend_django/books/urls.py
  backend_django/books/views.py
  backend_django/voe3Video/migrations/0003_video_character_video_thumbnail_url.py
  backend_django/voe3Video/models.py
Labels: feat

#62 [Fix] Gemini API로 대본생성/캐릭터생성 기능 마이그레이션
  backend_django/books/gemini_client.py
  backend_django/books/gpt_client.py
  backend_django/books/views.py
  backend_django/characters/gemini_client.py
  backend_django/characters/gpt_client.py
  backend_django/characters/migrations/0002_characterscene.py
  backend_django/characters/models.py
  backend_django/characters/views.py
  backend_django/config/settings_dev.py
  backend_django/config/settings_prod.py
  backend_django/docker-compose.dev.yml
  backend_django/requirements.txt
Labels: fix

#67 [feat] 영상 단건 조회 기능 구현
  backend_django/config/urls.py
  backend_django/voe3Video/serializers.py
  backend_django/voe3Video/urls.py
  backend_django/voe3Video/views.py
Labels: feat

#72 [Fix] 공용책 불러오기 pdf_url 수정
  backend_django/books/serializers.py
Labels: fix

#73 fix: 인증 기능에 csrf 허용
  backend_django/.dockerignore
  backend_django/config/settings_prod.py
  backend_django/docker-compose.prod.yml
  backend_django/users/views.py
Labels: fix

#69 [Feat] 영상 합치기 기능 구현
  backend_django/Dockerfile
  backend_django/books/serializers.py
  backend_django/books/views.py
  backend_django/config/celery.py
  backend_django/config/settings_dev.py
  backend_django/config/settings_prod.py
  backend_django/config/urls.py
  backend_django/docker-compose.dev.yml
  backend_django/docker-compose.prod.yml
  backend_django/requirements.txt
  backend_django/script_data.json
  backend_django/veo3Video/__init__.py
  backend_django/veo3Video/admin.py
  backend_django/veo3Video/apps.py
  backend_django/veo3Video/management/commands/import_gcs_videos.py
  backend_django/veo3Video/migrations/0001_initial.py
  backend_django/veo3Video/migrations/0002_alter_video_video_uri.py
  backend_django/veo3Video/migrations/0003_video_character_video_thumbnail_url.py
  backend_django/veo3Video/migrations/0004_video_narration_audio_url.py
  backend_django/veo3Video/migrations/__init__.py
  backend_django/veo3Video/models.py
  backend_django/veo3Video/serializers.py
  backend_django/veo3Video/tasks.py
  backend_django/veo3Video/tests.py
  backend_django/veo3Video/urls.py
  backend_django/veo3Video/veo_service.py
  backend_django/veo3Video/views.py
  backend_django/videos/admin.py
  backend_django/videos/apps.py
  backend_django/videos/migrations/__init__.py
  backend_django/videos/models.py
  backend_django/videos/services.py
  backend_django/videos/tests.py
  backend_django/videos/urls.py
  backend_django/videos/views.py
  backend_django/videos2/__init__.py
  backend_django/videos2/admin.py
  backend_django/videos2/migrations/__init__.py
  backend_django/videos2/models.py
  backend_django/videos2/tests.py
  backend_django/videos2/typecast_service.py
  backend_django/videos2/urls.py
  backend_django/videos2/views.py
  backend_django/voe3Video/apps.py
  backend_django/voe3Video/migrations/__init__.py
  backend_django/voe3Video/views.py
Labels: feat, fix

#82 [Fix] Video에 user_id 수정
  backend_django/veo3Video/migrations/0005_remove_video_user_id_video_user.py
  backend_django/veo3Video/models.py
  backend_django/veo3Video/tasks.py
  backend_django/veo3Video/veo_service.py
Labels: fix

#86 fix: env 파일명 변경, 배포용 도커 파일에 RabbitMq, Celery 설정
  backend_django/config/settings_prod.py
  backend_django/docker-compose.dev.yml
  backend_django/docker-compose.prod.yml
  backend_django/veo3Video/migrations/0006_merge_20250724_1351.py
Labels: devops

#90 [Fix] 책 PDF 입력 기능 비동기적으로 구현
  backend_django/books/migrations/0004_book_error_message_book_processing_status_and_more.py
  backend_django/books/models.py
  backend_django/books/serializers.py
  backend_django/books/tasks.py
  backend_django/books/urls.py
  backend_django/books/views.py
  backend_django/config/__init__.py
  backend_django/config/celery.py
  backend_django/config/settings_dev.py
Labels: fix

#92 [fix] 배포서버 405코드 해결
  backend_django/config/settings_prod.py
Labels: fix

#96 1. 영상 생성 시 중복 방지를 위한 넘버링 추가
  backend_django/veo3Video/tasks.py
  backend_django/veo3Video/veo_service.py
Labels: feat, fix

#101 devops: Celery Flower 설정, SSE 알림 방식 수정
  backend_django/books/eventstream_views.py
  backend_django/books/gemini_client.py
  backend_django/books/pdf_utils.py
  backend_django/books/tasks.py
  backend_django/books/urls.py
  backend_django/books/views.py
  backend_django/characters/tasks.py
  backend_django/characters/urls.py
  backend_django/config/asgi.py
  backend_django/config/celery.py
  backend_django/config/settings_dev.py
  backend_django/config/settings_prod.py
  backend_django/config/urls.py
  backend_django/docker-compose.dev.yml
  backend_django/docker-compose.prod.yml
  backend_django/prometheus/prometheus.yml
  backend_django/requirements.txt
  backend_django/veo3Video/migrations/0008_merge_20250728_0501.py
  backend_django/veo3Video/veo_service.py
Labels: feat, fix
